-- =============================================================================
-- PMS Mews Flight Recorder — snapshot + diff tables (lowercase quoted identifiers)
-- Generated by scripts/generate_pms_mews_sql.py — re-run after updating csv_samples
-- =============================================================================

-- pms_mews_accounting_categories_daily / pms_mews_accounting_categories_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_accounting_categories_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "name" VARCHAR(65535),
    "code" VARCHAR(65535),
    "external_code" VARCHAR(65535),
    "ledger_account_code" VARCHAR(65535),
    "posting_account_code" VARCHAR(65535),
    "cost_center_code" VARCHAR(65535),
    "classification" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_accounting_categories_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_availability_blocks_daily / pms_mews_availability_blocks_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_availability_blocks_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "service_id" VARCHAR(65535),
    "rate_id" VARCHAR(65535),
    "voucher_id" VARCHAR(65535),
    "booker_id" VARCHAR(65535),
    "company_id" VARCHAR(65535),
    "travel_agency_id" VARCHAR(65535),
    "budget" VARCHAR(65535),
    "state" VARCHAR(65535),
    "reservation_purpose" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "activity_state" VARCHAR(65535),
    "start_utc" VARCHAR(64),
    "end_utc" VARCHAR(64),
    "first_time_unit_start_utc" VARCHAR(64),
    "last_time_unit_start_utc" VARCHAR(64),
    "released_utc" VARCHAR(64),
    "rolling_release_offset" VARCHAR(65535),
    "external_identifier" VARCHAR(65535),
    "name" VARCHAR(65535),
    "notes" VARCHAR(65535),
    "pickup_distribution" VARCHAR(65535),
    "is_active" BOOLEAN,
    "quote_id" VARCHAR(65535),
    "availability_block_number" VARCHAR(65535),
    "release_strategy" VARCHAR(65535),
    "purchase_order_number" VARCHAR(65535),
    "business_segment_id" VARCHAR(65535),
    "canceled_utc" VARCHAR(64),
    "cancellation_reason" VARCHAR(65535),
    "cancellation_reason_detail" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_availability_blocks_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_bills_daily / pms_mews_bills_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_bills_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "name" VARCHAR(65535),
    "account_id" VARCHAR(65535),
    "account_type" VARCHAR(65535),
    "customer_id" VARCHAR(65535),
    "company_id" VARCHAR(65535),
    "associated_account_ids" VARCHAR(65535),
    "counter_id" VARCHAR(65535),
    "state" VARCHAR(65535),
    "type" VARCHAR(65535),
    "number" VARCHAR(65535),
    "variable_symbol" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "issued_utc" VARCHAR(64),
    "taxed_utc" VARCHAR(64),
    "paid_utc" VARCHAR(64),
    "due_utc" VARCHAR(64),
    "last_reminder_date_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "purchase_order_number" VARCHAR(65535),
    "notes" VARCHAR(65535),
    "options" VARCHAR(65535),
    "revenue" VARCHAR(65535),
    "payments" VARCHAR(65535),
    "order_items" VARCHAR(65535),
    "payment_items" VARCHAR(65535),
    "assignee_data" VARCHAR(65535),
    "owner_data" VARCHAR(65535),
    "company_details" VARCHAR(65535),
    "associated_account_data" VARCHAR(65535),
    "enterprise_data" VARCHAR(65535),
    "correction_state" VARCHAR(65535),
    "correction_type" VARCHAR(65535),
    "corrected_bill_id" VARCHAR(65535),
    "options_display_customer" VARCHAR(65535),
    "options_display_taxation" VARCHAR(65535),
    "options_track_receivable" VARCHAR(65535),
    "options_display_cid" VARCHAR(65535),
    "options_rebated" VARCHAR(65535),
    "assignee_data_discriminator" VARCHAR(65535),
    "assignee_data_value_italian_fiscal_code" VARCHAR(65535),
    "assignee_data_value_italian_lottery_code" VARCHAR(65535),
    "owner_data_discriminator" VARCHAR(65535),
    "owner_data_value_id" VARCHAR(65535),
    "owner_data_value_address_line1" VARCHAR(65535),
    "owner_data_value_address_line2" VARCHAR(65535),
    "owner_data_value_address_city" VARCHAR(65535),
    "owner_data_value_address_postal_code" VARCHAR(65535),
    "owner_data_value_address_subdivision_code" VARCHAR(65535),
    "owner_data_value_address_country_code" VARCHAR(65535),
    "owner_data_value_billing_code" VARCHAR(65535),
    "owner_data_value_last_name" VARCHAR(65535),
    "owner_data_value_first_name" VARCHAR(65535),
    "owner_data_value_second_last_name" VARCHAR(65535),
    "owner_data_value_title_prefix" VARCHAR(65535),
    "owner_data_value_tax_identifier" VARCHAR(65535),
    "enterprise_data_additional_tax_identifier" VARCHAR(65535),
    "enterprise_data_company_name" VARCHAR(65535),
    "enterprise_data_bank_account" VARCHAR(65535),
    "enterprise_data_bank_name" VARCHAR(65535),
    "enterprise_data_iban" VARCHAR(65535),
    "enterprise_data_bic" VARCHAR(65535),
    "assignee_data_value_id" VARCHAR(65535),
    "assignee_data_value_address_line1" VARCHAR(65535),
    "assignee_data_value_address_line2" VARCHAR(65535),
    "assignee_data_value_address_city" VARCHAR(65535),
    "assignee_data_value_address_postal_code" VARCHAR(65535),
    "assignee_data_value_address_subdivision_code" VARCHAR(65535),
    "assignee_data_value_address_country_code" VARCHAR(65535),
    "assignee_data_value_billing_code" VARCHAR(65535),
    "assignee_data_value_name" VARCHAR(65535),
    "assignee_data_value_fiscal_identifier" VARCHAR(65535),
    "assignee_data_value_additional_tax_identifier" VARCHAR(65535),
    "assignee_data_value_duns" VARCHAR(65535),
    "assignee_data_value_telephone" VARCHAR(65535),
    "assignee_data_value_tax_identifier" VARCHAR(65535),
    "assignee_data_value_invoicing_email" VARCHAR(65535),
    "assignee_data_value_department" VARCHAR(65535),
    "owner_data_value_name" VARCHAR(65535),
    "owner_data_value_fiscal_identifier" VARCHAR(65535),
    "owner_data_value_additional_tax_identifier" VARCHAR(65535),
    "owner_data_value_duns" VARCHAR(65535),
    "owner_data_value_telephone" VARCHAR(65535),
    "owner_data_value_invoicing_email" VARCHAR(65535),
    "owner_data_value_department" VARCHAR(65535),
    "company_details_id" VARCHAR(65535),
    "company_details_address_line1" VARCHAR(65535),
    "company_details_address_line2" VARCHAR(65535),
    "company_details_address_city" VARCHAR(65535),
    "company_details_address_postal_code" VARCHAR(65535),
    "company_details_address_subdivision_code" VARCHAR(65535),
    "company_details_address_country_code" VARCHAR(65535),
    "company_details_billing_code" VARCHAR(65535),
    "company_details_name" VARCHAR(65535),
    "company_details_fiscal_identifier" VARCHAR(65535),
    "company_details_additional_tax_identifier" VARCHAR(65535),
    "company_details_duns" VARCHAR(65535),
    "company_details_telephone" VARCHAR(65535),
    "company_details_tax_identifier" VARCHAR(65535),
    "company_details_invoicing_email" VARCHAR(65535),
    "company_details_department" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_bills_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_business_segments_daily / pms_mews_business_segments_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_business_segments_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "service_id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "name" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_business_segments_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_cashiers_daily / pms_mews_cashiers_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_cashiers_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "name" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_cashiers_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_companies_daily / pms_mews_companies_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_companies_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "chain_id" VARCHAR(65535),
    "name" VARCHAR(65535),
    "mother_company_id" VARCHAR(65535),
    "invoicing_email" VARCHAR(65535),
    "website_url" VARCHAR(65535),
    "invoice_due_interval" VARCHAR(65535),
    "department" VARCHAR(65535),
    "duns_number" VARCHAR(65535),
    "reference_identifier" VARCHAR(65535),
    "accounting_code" VARCHAR(65535),
    "additional_tax_identifier" VARCHAR(65535),
    "billing_code" VARCHAR(65535),
    "contact" VARCHAR(65535),
    "contact_person" VARCHAR(65535),
    "electronic_invoice_identifier" VARCHAR(65535),
    "identifier" VARCHAR(65535),
    "iata" VARCHAR(65535),
    "is_active" BOOLEAN,
    "notes" VARCHAR(65535),
    "number" VARCHAR(65535),
    "tax_identifier" VARCHAR(65535),
    "telephone" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "address" VARCHAR(65535),
    "address_id" VARCHAR(65535),
    "merge_target_id" VARCHAR(65535),
    "tax_identification_number" VARCHAR(65535),
    "external_identifier" VARCHAR(65535),
    "is_updated_by_me" BOOLEAN,
    "nch_classifications_corporate" VARCHAR(65535),
    "nch_classifications_internal" VARCHAR(65535),
    "nch_classifications_private" VARCHAR(65535),
    "nch_classifications_online_travel_agency" VARCHAR(65535),
    "nch_classifications_global_distribution_system" VARCHAR(65535),
    "nch_classifications_marketing" VARCHAR(65535),
    "nch_classifications_inactive" VARCHAR(65535),
    "nch_classifications_government_entity" VARCHAR(65535),
    "options_invoiceable" VARCHAR(65535),
    "options_add_fees_to_invoices" VARCHAR(65535),
    "options_add_tax_deducted_payment_to_invoices" VARCHAR(65535),
    "credit_rating_basic" VARCHAR(65535),
    "address_line1" VARCHAR(65535),
    "address_line2" VARCHAR(65535),
    "address_city" VARCHAR(65535),
    "address_postal_code" VARCHAR(65535),
    "address_country_code" VARCHAR(65535),
    "address_country_subdivision_code" VARCHAR(65535),
    "address_latitude" FLOAT,
    "address_longitude" FLOAT,
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_companies_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_companionships_daily / pms_mews_companionships_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_companionships_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "customer_id" VARCHAR(65535),
    "reservation_group_id" VARCHAR(65535),
    "reservation_id" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_companionships_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_configuration_daily / pms_mews_configuration_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_configuration_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "now_utc" VARCHAR(64),
    "service" VARCHAR(65535),
    "payment_card_storage" VARCHAR(65535),
    "is_identity_document_number_required" BOOLEAN,
    "enterprise_currencies" VARCHAR(65535),
    "enterprise_accounting_configuration_additional_tax_identifier" VARCHAR(65535),
    "enterprise_accounting_configuration_company_name" VARCHAR(65535),
    "enterprise_accounting_configuration_bank_account_number" VARCHAR(65535),
    "enterprise_accounting_configuration_bank_name" VARCHAR(65535),
    "enterprise_accounting_configuration_iban" VARCHAR(65535),
    "enterprise_accounting_configuration_bic" VARCHAR(65535),
    "enterprise_accounting_configuration_surcharge_configuration_surcharge_service_id" VARCHAR(65535),
    "enterprise_accounting_configuration_surcharge_configuration_surcharge_tax_code" VARCHAR(65535),
    "enterprise_accounting_configuration_enabled_external_payment_types" VARCHAR(65535),
    "enterprise_accounting_configuration_options" VARCHAR(65535),
    "enterprise_is_portfolio" BOOLEAN,
    "enterprise_external_identifier" VARCHAR(65535),
    "enterprise_holding_key" VARCHAR(65535),
    "enterprise_chain_id" VARCHAR(65535),
    "enterprise_chain_name" VARCHAR(65535),
    "enterprise_created_utc" VARCHAR(64),
    "enterprise_updated_utc" VARCHAR(64),
    "enterprise_name" VARCHAR(65535),
    "enterprise_time_zone_identifier" VARCHAR(65535),
    "enterprise_legal_environment_code" VARCHAR(65535),
    "enterprise_accommodation_environment_code" VARCHAR(65535),
    "enterprise_accounting_environment_code" VARCHAR(65535),
    "enterprise_tax_environment_code" VARCHAR(65535),
    "enterprise_default_language_code" VARCHAR(65535),
    "enterprise_editable_history_interval" VARCHAR(65535),
    "enterprise_accounting_editable_history_interval" VARCHAR(65535),
    "enterprise_operational_editable_history_interval" VARCHAR(65535),
    "enterprise_business_day_closing_offset" VARCHAR(65535),
    "enterprise_website_url" VARCHAR(65535),
    "enterprise_email" VARCHAR(65535),
    "enterprise_phone" VARCHAR(65535),
    "enterprise_logo_image_id" VARCHAR(65535),
    "enterprise_cover_image_id" VARCHAR(65535),
    "enterprise_pricing" VARCHAR(65535),
    "enterprise_tax_precision" VARCHAR(65535),
    "enterprise_address_id" VARCHAR(65535),
    "enterprise_address_line1" VARCHAR(65535),
    "enterprise_address_line2" VARCHAR(65535),
    "enterprise_address_city" VARCHAR(65535),
    "enterprise_address_postal_code" VARCHAR(65535),
    "enterprise_address_country_code" VARCHAR(65535),
    "enterprise_address_country_subdivision_code" VARCHAR(65535),
    "enterprise_address_latitude" FLOAT,
    "enterprise_address_longitude" FLOAT,
    "enterprise_group_names" VARCHAR(65535),
    "enterprise_subscription_tax_identifier" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_configuration_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_counters_daily / pms_mews_counters_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_counters_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "name" VARCHAR(65535),
    "is_default" BOOLEAN,
    "value" VARCHAR(65535),
    "format" VARCHAR(65535),
    "type" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_counters_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_countries_daily / pms_mews_countries_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_countries_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "code" VARCHAR(65535),
    "sovereign_country_code" VARCHAR(65535),
    "english_name" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_countries_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_credit_cards_daily / pms_mews_credit_cards_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_credit_cards_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "customer_id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "state" VARCHAR(65535),
    "kind" VARCHAR(65535),
    "format" VARCHAR(65535),
    "type" VARCHAR(65535),
    "obfuscated_number" VARCHAR(65535),
    "expiration" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_credit_cards_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_currencies_daily / pms_mews_currencies_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_currencies_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "code" VARCHAR(65535),
    "precision" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_currencies_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_customers_daily / pms_mews_customers_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_customers_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "chain_id" VARCHAR(65535),
    "number" VARCHAR(65535),
    "title" VARCHAR(65535),
    "sex" VARCHAR(65535),
    "gender" VARCHAR(65535),
    "first_name" VARCHAR(65535),
    "last_name" VARCHAR(65535),
    "second_last_name" VARCHAR(65535),
    "nationality_code" VARCHAR(65535),
    "preferred_language_code" VARCHAR(65535),
    "language_code" VARCHAR(65535),
    "birth_date" VARCHAR(65535),
    "birth_country_code" VARCHAR(65535),
    "birth_country_subdivision_code" VARCHAR(65535),
    "birth_place" VARCHAR(65535),
    "occupation" VARCHAR(65535),
    "email" VARCHAR(65535),
    "has_ota_email" BOOLEAN,
    "phone" VARCHAR(65535),
    "tax_identification_number" VARCHAR(65535),
    "loyalty_code" VARCHAR(65535),
    "accounting_code" VARCHAR(65535),
    "billing_code" VARCHAR(65535),
    "notes" VARCHAR(65535),
    "car_registration_number" VARCHAR(65535),
    "dietary_requirements" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "passport" VARCHAR(65535),
    "identity_card" VARCHAR(65535),
    "visa" VARCHAR(65535),
    "drivers_license" VARCHAR(65535),
    "address" VARCHAR(65535),
    "address_id" VARCHAR(65535),
    "classifications" VARCHAR(65535),
    "options" VARCHAR(65535),
    "category_id" VARCHAR(65535),
    "birth_date_utc" VARCHAR(64),
    "italian_destination_code" VARCHAR(65535),
    "italian_fiscal_code" VARCHAR(65535),
    "italian_lottery_code" VARCHAR(65535),
    "company_id" VARCHAR(65535),
    "merge_target_id" VARCHAR(65535),
    "activity_state" VARCHAR(65535),
    "is_active" BOOLEAN,
    "is_updated_by_me" BOOLEAN,
    "preferred_space_features" VARCHAR(65535),
    "creator_profile_id" VARCHAR(65535),
    "updater_profile_id" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_customers_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_departments_daily / pms_mews_departments_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_departments_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "name" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_departments_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_enterprises_daily / pms_mews_enterprises_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_enterprises_daily (
    "snapshot_date" DATE NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "linked_utc" VARCHAR(64),
    "id" VARCHAR(65535),
    "external_identifier" VARCHAR(65535),
    "holding_key" VARCHAR(65535),
    "chain_id" VARCHAR(65535),
    "chain_name" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "name" VARCHAR(65535),
    "time_zone_identifier" VARCHAR(65535),
    "legal_environment_code" VARCHAR(65535),
    "accommodation_environment_code" VARCHAR(65535),
    "accounting_environment_code" VARCHAR(65535),
    "tax_environment_code" VARCHAR(65535),
    "default_language_code" VARCHAR(65535),
    "editable_history_interval" VARCHAR(65535),
    "accounting_editable_history_interval" VARCHAR(65535),
    "operational_editable_history_interval" VARCHAR(65535),
    "business_day_closing_offset" VARCHAR(65535),
    "website_url" VARCHAR(65535),
    "email" VARCHAR(65535),
    "phone" VARCHAR(65535),
    "logo_image_id" VARCHAR(65535),
    "cover_image_id" VARCHAR(65535),
    "pricing" VARCHAR(65535),
    "tax_precision" VARCHAR(65535),
    "address_id" VARCHAR(65535),
    "group_names" VARCHAR(65535),
    "address_line1" VARCHAR(65535),
    "address_line2" VARCHAR(65535),
    "address_city" VARCHAR(65535),
    "address_postal_code" VARCHAR(65535),
    "address_country_code" VARCHAR(65535),
    "address_country_subdivision_code" VARCHAR(65535),
    "address_latitude" FLOAT,
    "address_longitude" FLOAT,
    "subscription_tax_identifier" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_enterprises_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "entity_id", "changed_metric_name")
);

-- pms_mews_exchange_rates_daily / pms_mews_exchange_rates_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_exchange_rates_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "source_currency" VARCHAR(65535),
    "target_currency" VARCHAR(65535),
    "value" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_exchange_rates_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_exports_daily / pms_mews_exports_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_exports_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "status" VARCHAR(65535),
    "entity_type" VARCHAR(65535),
    "files" VARCHAR(65535),
    "expires_utc" VARCHAR(64),
    "scope_enterprise_ids" VARCHAR(65535),
    "scope_chain_ids" VARCHAR(65535),
    "filters_updated_utc_start_utc" VARCHAR(64),
    "filters_updated_utc_end_utc" VARCHAR(64),
    "filters_ledger_entry_filters" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_exports_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_languages_daily / pms_mews_languages_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_languages_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "code" VARCHAR(65535),
    "fallback_language_code" VARCHAR(65535),
    "english_name" VARCHAR(65535),
    "local_name" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_languages_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_loyalty_memberships_daily / pms_mews_loyalty_memberships_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_loyalty_memberships_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "chain_id" VARCHAR(65535),
    "account_id" VARCHAR(65535),
    "loyalty_program_id" VARCHAR(65535),
    "state" VARCHAR(65535),
    "is_primary" BOOLEAN,
    "provider_membership_id" VARCHAR(65535),
    "code" VARCHAR(65535),
    "membership_number" VARCHAR(65535),
    "points" VARCHAR(65535),
    "expiration_date" VARCHAR(65535),
    "url" VARCHAR(65535),
    "loyalty_tier_id" VARCHAR(65535),
    "creator_profile_discriminator" VARCHAR(65535),
    "creator_profile_enterprise_profile" VARCHAR(65535),
    "updater_profile_discriminator" VARCHAR(65535),
    "updater_profile_enterprise_profile" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_loyalty_memberships_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_loyalty_programs_daily / pms_mews_loyalty_programs_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_loyalty_programs_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "chain_id" VARCHAR(65535),
    "name" VARCHAR(65535),
    "code" VARCHAR(65535),
    "type" VARCHAR(65535),
    "subscription" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_loyalty_programs_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_order_items_daily / pms_mews_order_items_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_order_items_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "account_id" VARCHAR(65535),
    "account_type" VARCHAR(65535),
    "service_id" VARCHAR(65535),
    "service_order_id" VARCHAR(65535),
    "notes" VARCHAR(65535),
    "bill_id" VARCHAR(65535),
    "accounting_category_id" VARCHAR(65535),
    "billing_name" VARCHAR(65535),
    "external_identifier" VARCHAR(65535),
    "unit_count" VARCHAR(65535),
    "revenue_type" VARCHAR(65535),
    "creator_profile_id" VARCHAR(65535),
    "updater_profile_id" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "consumed_utc" VARCHAR(64),
    "canceled_utc" VARCHAR(64),
    "closed_utc" VARCHAR(64),
    "start_utc" VARCHAR(64),
    "claimed_utc" VARCHAR(64),
    "accounting_state" VARCHAR(65535),
    "type" VARCHAR(65535),
    "tax_exemption_reason" VARCHAR(65535),
    "tax_exemption_legal_reference" VARCHAR(65535),
    "unit_amount_currency" VARCHAR(65535),
    "unit_amount_net_value" VARCHAR(65535),
    "unit_amount_gross_value" VARCHAR(65535),
    "unit_amount_tax_values" VARCHAR(65535),
    "unit_amount_breakdown_items" VARCHAR(65535),
    "amount_currency" VARCHAR(65535),
    "amount_net_value" VARCHAR(65535),
    "amount_gross_value" VARCHAR(65535),
    "amount_tax_values" VARCHAR(65535),
    "amount_breakdown_items" VARCHAR(65535),
    "original_amount_currency" VARCHAR(65535),
    "original_amount_net_value" VARCHAR(65535),
    "original_amount_gross_value" VARCHAR(65535),
    "original_amount_tax_values" VARCHAR(65535),
    "original_amount_breakdown_items" VARCHAR(65535),
    "options_canceled_with_reservation" VARCHAR(65535),
    "data_discriminator" VARCHAR(65535),
    "data_rebate" VARCHAR(65535),
    "data_product_product_id" VARCHAR(65535),
    "data_product_age_category_id" VARCHAR(65535),
    "data_product_product_type" VARCHAR(65535),
    "data_allowance_discount" VARCHAR(65535),
    "data_allowance_profits" VARCHAR(65535),
    "data" VARCHAR(65535),
    "data_rebate_product_id" VARCHAR(65535),
    "data_rebate_rebated_item_id" VARCHAR(65535),
    "data_product" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_order_items_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_outlets_daily / pms_mews_outlets_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_outlets_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "name" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_outlets_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_payment_requests_daily / pms_mews_payment_requests_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_payment_requests_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "account_id" VARCHAR(65535),
    "customer_id" VARCHAR(65535),
    "reservation_group_id" VARCHAR(65535),
    "reservation_id" VARCHAR(65535),
    "state" VARCHAR(65535),
    "type" VARCHAR(65535),
    "reason" VARCHAR(65535),
    "expiration_utc" VARCHAR(64),
    "description" VARCHAR(65535),
    "notes" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "amount_currency" VARCHAR(65535),
    "amount_net_value" VARCHAR(65535),
    "amount_gross_value" VARCHAR(65535),
    "amount_tax_values" VARCHAR(65535),
    "amount_breakdown_items" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_payment_requests_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_product_service_orders_daily / pms_mews_product_service_orders_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_product_service_orders_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "service_id" VARCHAR(65535),
    "account_id" VARCHAR(65535),
    "account_type" VARCHAR(65535),
    "creator_profile_id" VARCHAR(65535),
    "updater_profile_id" VARCHAR(65535),
    "booker_id" VARCHAR(65535),
    "number" VARCHAR(65535),
    "state" VARCHAR(65535),
    "origin" VARCHAR(65535),
    "commander_origin" VARCHAR(65535),
    "origin_details" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "cancelled_utc" VARCHAR(64),
    "voucher_id" VARCHAR(65535),
    "business_segment_id" VARCHAR(65535),
    "linked_reservation_id" VARCHAR(65535),
    "options_owner_checked_in" VARCHAR(65535),
    "options_all_companions_checked_in" VARCHAR(65535),
    "options_any_companion_checked_in" VARCHAR(65535),
    "options_connector_check_in" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_product_service_orders_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_rates_daily / pms_mews_rates_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_rates_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "group_id" VARCHAR(65535),
    "service_id" VARCHAR(65535),
    "base_rate_id" VARCHAR(65535),
    "is_base_rate" BOOLEAN,
    "business_segment_id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "is_enabled" BOOLEAN,
    "is_public" BOOLEAN,
    "is_default" BOOLEAN,
    "type" VARCHAR(65535),
    "name" VARCHAR(65535),
    "short_name" VARCHAR(65535),
    "updated_utc" VARCHAR(64),
    "external_identifier" VARCHAR(65535),
    "tax_exemption_reason" VARCHAR(65535),
    "tax_exemption_legal_reference" VARCHAR(65535),
    "names_en_us" VARCHAR(65535),
    "options_hide_price_from_guest" VARCHAR(65535),
    "options_is_bonus_points_eligible" BOOLEAN,
    "pricing_discriminator" VARCHAR(65535),
    "pricing_base_rate_pricing_amount_currency" VARCHAR(65535),
    "pricing_base_rate_pricing_amount_net_value" VARCHAR(65535),
    "pricing_base_rate_pricing_amount_gross_value" VARCHAR(65535),
    "pricing_base_rate_pricing_amount_tax_values" VARCHAR(65535),
    "pricing_base_rate_pricing_amount_breakdown_items" VARCHAR(65535),
    "pricing_dependent_rate_pricing" VARCHAR(65535),
    "external_names_en_us" VARCHAR(65535),
    "description_en_us" VARCHAR(65535),
    "pricing_base_rate_pricing" VARCHAR(65535),
    "pricing_dependent_rate_pricing_base_rate_id" VARCHAR(65535),
    "pricing_dependent_rate_pricing_relative_adjustment" VARCHAR(65535),
    "pricing_dependent_rate_pricing_absolute_adjustment" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_rates_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_reservation_groups_daily / pms_mews_reservation_groups_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_reservation_groups_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "name" VARCHAR(65535),
    "channel_manager" VARCHAR(65535),
    "channel_manager_group_number" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_reservation_groups_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_reservations_daily / pms_mews_reservations_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_reservations_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "service_id" VARCHAR(65535),
    "account_id" VARCHAR(65535),
    "account_type" VARCHAR(65535),
    "creator_profile_id" VARCHAR(65535),
    "updater_profile_id" VARCHAR(65535),
    "booker_id" VARCHAR(65535),
    "number" VARCHAR(65535),
    "state" VARCHAR(65535),
    "origin" VARCHAR(65535),
    "commander_origin" VARCHAR(65535),
    "origin_details" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "cancelled_utc" VARCHAR(64),
    "voucher_id" VARCHAR(65535),
    "business_segment_id" VARCHAR(65535),
    "rate_id" VARCHAR(65535),
    "credit_card_id" VARCHAR(65535),
    "group_id" VARCHAR(65535),
    "requested_resource_category_id" VARCHAR(65535),
    "assigned_resource_id" VARCHAR(65535),
    "availability_block_id" VARCHAR(65535),
    "partner_company_id" VARCHAR(65535),
    "travel_agency_id" VARCHAR(65535),
    "assigned_resource_locked" VARCHAR(65535),
    "channel_number" VARCHAR(65535),
    "channel_manager_number" VARCHAR(65535),
    "cancellation_reason" VARCHAR(65535),
    "released_utc" VARCHAR(64),
    "start_utc" VARCHAR(64),
    "end_utc" VARCHAR(64),
    "scheduled_start_utc" VARCHAR(64),
    "actual_start_utc" VARCHAR(64),
    "scheduled_end_utc" VARCHAR(64),
    "actual_end_utc" VARCHAR(64),
    "purpose" VARCHAR(65535),
    "qr_code_data" VARCHAR(65535),
    "person_counts" VARCHAR(65535),
    "options_owner_checked_in" VARCHAR(65535),
    "options_all_companions_checked_in" VARCHAR(65535),
    "options_any_companion_checked_in" VARCHAR(65535),
    "options_connector_check_in" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_reservations_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_resource_blocks_daily / pms_mews_resource_blocks_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_resource_blocks_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "assigned_resource_id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "type" VARCHAR(65535),
    "start_utc" VARCHAR(64),
    "end_utc" VARCHAR(64),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "deleted_utc" VARCHAR(64),
    "name" VARCHAR(65535),
    "notes" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_resource_blocks_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_resource_categories_daily / pms_mews_resource_categories_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_resource_categories_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "service_id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "type" VARCHAR(65535),
    "classification" VARCHAR(65535),
    "ordering" VARCHAR(65535),
    "capacity" VARCHAR(65535),
    "extra_capacity" VARCHAR(65535),
    "external_identifier" VARCHAR(65535),
    "accounting_category_id" VARCHAR(65535),
    "names_en_us" VARCHAR(65535),
    "short_names_en_us" VARCHAR(65535),
    "descriptions_en_us" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_resource_categories_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_resource_category_assignments_daily / pms_mews_resource_category_assignments_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_resource_category_assignments_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "resource_id" VARCHAR(65535),
    "category_id" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_resource_category_assignments_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_resource_category_image_assignments_daily / pms_mews_resource_category_image_assignments_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_resource_category_image_assignments_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "category_id" VARCHAR(65535),
    "image_id" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "ordering" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_resource_category_image_assignments_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_resource_feature_assignments_daily / pms_mews_resource_feature_assignments_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_resource_feature_assignments_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "resource_id" VARCHAR(65535),
    "feature_id" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_resource_feature_assignments_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_resource_features_daily / pms_mews_resource_features_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_resource_features_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "service_id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "classification" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "names_en_us" VARCHAR(65535),
    "short_names_en_us" VARCHAR(65535),
    "descriptions_en_us" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_resource_features_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_resources_daily / pms_mews_resources_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_resources_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "parent_resource_id" VARCHAR(65535),
    "name" VARCHAR(65535),
    "state" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "descriptions_en_us" VARCHAR(65535),
    "data_discriminator" VARCHAR(65535),
    "data_value_floor_number" VARCHAR(65535),
    "data_value_location_notes" VARCHAR(65535),
    "external_names_en_us" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_resources_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_restrictions_daily / pms_mews_restrictions_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_restrictions_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "service_id" VARCHAR(65535),
    "external_identifier" VARCHAR(65535),
    "origin" VARCHAR(65535),
    "conditions_type" VARCHAR(65535),
    "conditions_exact_rate_id" VARCHAR(65535),
    "conditions_base_rate_id" VARCHAR(65535),
    "conditions_rate_group_id" VARCHAR(65535),
    "conditions_resource_category_id" VARCHAR(65535),
    "conditions_resource_category_type" VARCHAR(65535),
    "conditions_start_utc" VARCHAR(64),
    "conditions_end_utc" VARCHAR(64),
    "conditions_days" VARCHAR(65535),
    "conditions_hours_zero" VARCHAR(65535),
    "conditions_hours_one" VARCHAR(65535),
    "conditions_hours_two" VARCHAR(65535),
    "conditions_hours_three" VARCHAR(65535),
    "conditions_hours_four" VARCHAR(65535),
    "conditions_hours_five" VARCHAR(65535),
    "conditions_hours_six" VARCHAR(65535),
    "conditions_hours_seven" VARCHAR(65535),
    "conditions_hours_eight" VARCHAR(65535),
    "conditions_hours_nine" VARCHAR(65535),
    "conditions_hours_ten" VARCHAR(65535),
    "conditions_hours_eleven" VARCHAR(65535),
    "conditions_hours_twelve" VARCHAR(65535),
    "conditions_hours_thirteen" VARCHAR(65535),
    "conditions_hours_fourteen" VARCHAR(65535),
    "conditions_hours_fifteen" VARCHAR(65535),
    "conditions_hours_sixteen" VARCHAR(65535),
    "conditions_hours_seventeen" VARCHAR(65535),
    "conditions_hours_eighteen" VARCHAR(65535),
    "conditions_hours_nineteen" VARCHAR(65535),
    "conditions_hours_twenty" VARCHAR(65535),
    "conditions_hours_twenty_one" VARCHAR(65535),
    "conditions_hours_twenty_two" VARCHAR(65535),
    "conditions_hours_twenty_three" VARCHAR(65535),
    "exceptions_min_advance" VARCHAR(65535),
    "exceptions_max_advance" VARCHAR(65535),
    "exceptions_min_length" VARCHAR(65535),
    "exceptions_max_length" VARCHAR(65535),
    "exceptions_min_price" VARCHAR(65535),
    "exceptions_max_price" VARCHAR(65535),
    "exceptions_min_reservation_count" VARCHAR(65535),
    "exceptions_max_reservation_count" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_restrictions_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_service_order_notes_daily / pms_mews_service_order_notes_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_service_order_notes_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "order_id" VARCHAR(65535),
    "text" VARCHAR(65535),
    "type" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_service_order_notes_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_services_daily / pms_mews_services_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_services_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "is_active" BOOLEAN,
    "name" VARCHAR(65535),
    "start_time" VARCHAR(65535),
    "end_time" VARCHAR(65535),
    "type" VARCHAR(65535),
    "ordering" VARCHAR(65535),
    "external_identifier" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "names_en_us" VARCHAR(65535),
    "options_bill_as_package" VARCHAR(65535),
    "promotions_before_check_in" VARCHAR(65535),
    "promotions_after_check_in" VARCHAR(65535),
    "promotions_during_stay" VARCHAR(65535),
    "promotions_before_check_out" VARCHAR(65535),
    "promotions_after_check_out" VARCHAR(65535),
    "promotions_during_check_out" VARCHAR(65535),
    "data_discriminator" VARCHAR(65535),
    "data_value_promotions_before_check_in" VARCHAR(65535),
    "data_value_promotions_after_check_in" VARCHAR(65535),
    "data_value_promotions_during_stay" VARCHAR(65535),
    "data_value_promotions_before_check_out" VARCHAR(65535),
    "data_value_promotions_after_check_out" VARCHAR(65535),
    "data_value_promotions_during_check_out" VARCHAR(65535),
    "promotions" VARCHAR(65535),
    "data_value_start_offset" VARCHAR(65535),
    "data_value_end_offset" VARCHAR(65535),
    "data_value_occupancy_start_offset" VARCHAR(65535),
    "data_value_occupancy_end_offset" VARCHAR(65535),
    "data_value_time_unit" VARCHAR(65535),
    "data_value_time_unit_period" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_services_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_services_get_availability_daily / pms_mews_services_get_availability_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_services_get_availability_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "dates_utc" VARCHAR(64),
    "time_unit_starts_utc" VARCHAR(64),
    "category_availabilities" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_services_get_availability_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_source_assignments_daily / pms_mews_source_assignments_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_source_assignments_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "reservation_group_id" VARCHAR(65535),
    "source_id" VARCHAR(65535),
    "is_primary" BOOLEAN,
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_source_assignments_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_sources_daily / pms_mews_sources_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_sources_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "name" VARCHAR(65535),
    "type" VARCHAR(65535),
    "updated_utc" VARCHAR(64),
    "code" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_sources_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_tasks_daily / pms_mews_tasks_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_tasks_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "name" VARCHAR(65535),
    "state" VARCHAR(65535),
    "description" VARCHAR(65535),
    "department_id" VARCHAR(65535),
    "service_order_id" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "deadline_utc" VARCHAR(64),
    "closed_utc" VARCHAR(64),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_tasks_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_tax_environments_daily / pms_mews_tax_environments_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_tax_environments_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "code" VARCHAR(65535),
    "country_code" VARCHAR(65535),
    "validity_start_utc" VARCHAR(64),
    "validity_end_utc" VARCHAR(64),
    "taxation_codes" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_tax_environments_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_taxations_daily / pms_mews_taxations_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_taxations_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "code" VARCHAR(65535),
    "name" VARCHAR(65535),
    "local_name" VARCHAR(65535),
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_taxations_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_vouchers_daily / pms_mews_vouchers_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_vouchers_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "id" VARCHAR(65535),
    "service_id" VARCHAR(65535),
    "name" VARCHAR(65535),
    "created_utc" VARCHAR(64),
    "updated_utc" VARCHAR(64),
    "type" VARCHAR(65535),
    "activity_state" VARCHAR(65535),
    "company_id" VARCHAR(65535),
    "travel_agency_id" VARCHAR(65535),
    "occupiable_interval_start_utc" VARCHAR(64),
    "occupiable_interval_end_utc" VARCHAR(64),
    "external_identifier" VARCHAR(65535),
    "is_active" BOOLEAN,
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_vouchers_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_company_contracts_daily / pms_mews_company_contracts_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_company_contracts_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_company_contracts_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_devices_daily / pms_mews_devices_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_devices_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_devices_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_commands_daily / pms_mews_commands_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_commands_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_commands_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_cashier_transactions_daily / pms_mews_cashier_transactions_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_cashier_transactions_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_cashier_transactions_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_outlet_items_daily / pms_mews_outlet_items_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_outlet_items_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_outlet_items_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_payments_daily / pms_mews_payments_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_payments_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_payments_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_preauthorizations_daily / pms_mews_preauthorizations_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_preauthorizations_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_preauthorizations_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_products_daily / pms_mews_products_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_products_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_products_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_rules_daily / pms_mews_rules_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_rules_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_rules_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_resource_access_tokens_daily / pms_mews_resource_access_tokens_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_resource_access_tokens_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_resource_access_tokens_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_message_threads_daily / pms_mews_message_threads_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_message_threads_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_message_threads_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_messages_daily / pms_mews_messages_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_messages_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_messages_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_routing_rules_daily / pms_mews_routing_rules_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_routing_rules_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_routing_rules_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_reservation_prices_daily / pms_mews_reservation_prices_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_reservation_prices_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_reservation_prices_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_customers_search_daily / pms_mews_customers_search_diff_daily
CREATE TABLE IF NOT EXISTS pms_mews_customers_search_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS pms_mews_customers_search_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);

-- pms_mews_rates_get_pricing_daily / pms_mews_rates_get_pricing_diff_daily
-- rates/getPricing (Connector API): Currency, DatesUtc, TimeUnitStartsUtc, BasePrices,
-- BaseAmountPrices, CategoryPrices, CategoryAdjustments, AgeCategoryAdjustments, adjustments
CREATE TABLE IF NOT EXISTS pms_mews_rates_get_pricing_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,

    "currency" VARCHAR(16),
    "dates_utc" VARIANT,
    "time_unit_starts_utc" VARIANT,
    "base_prices" VARIANT,
    "base_amount_prices" VARIANT,
    "category_prices" VARIANT,
    "category_adjustments" VARIANT,
    "age_category_adjustments" VARIANT,
    "relative_adjustment" FLOAT,
    "absolute_adjustment" FLOAT,
    "empty_unit_adjustment" FLOAT,
    "extra_unit_adjustment" FLOAT,
    "record_json" VARIANT NOT NULL,
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id")
);

-- Legacy table upgrade (run once if daily table existed with only record_json):
-- ALTER TABLE pms_mews_rates_get_pricing_daily ADD COLUMN IF NOT EXISTS "currency" VARCHAR(16);
-- ALTER TABLE pms_mews_rates_get_pricing_daily ADD COLUMN IF NOT EXISTS "dates_utc" VARIANT;
-- ALTER TABLE pms_mews_rates_get_pricing_daily ADD COLUMN IF NOT EXISTS "time_unit_starts_utc" VARIANT;
-- ALTER TABLE pms_mews_rates_get_pricing_daily ADD COLUMN IF NOT EXISTS "base_prices" VARIANT;
-- ALTER TABLE pms_mews_rates_get_pricing_daily ADD COLUMN IF NOT EXISTS "base_amount_prices" VARIANT;
-- ALTER TABLE pms_mews_rates_get_pricing_daily ADD COLUMN IF NOT EXISTS "category_prices" VARIANT;
-- ALTER TABLE pms_mews_rates_get_pricing_daily ADD COLUMN IF NOT EXISTS "category_adjustments" VARIANT;
-- ALTER TABLE pms_mews_rates_get_pricing_daily ADD COLUMN IF NOT EXISTS "age_category_adjustments" VARIANT;
-- ALTER TABLE pms_mews_rates_get_pricing_daily ADD COLUMN IF NOT EXISTS "relative_adjustment" FLOAT;
-- ALTER TABLE pms_mews_rates_get_pricing_daily ADD COLUMN IF NOT EXISTS "absolute_adjustment" FLOAT;
-- ALTER TABLE pms_mews_rates_get_pricing_daily ADD COLUMN IF NOT EXISTS "empty_unit_adjustment" FLOAT;
-- ALTER TABLE pms_mews_rates_get_pricing_daily ADD COLUMN IF NOT EXISTS "extra_unit_adjustment" FLOAT;

CREATE TABLE IF NOT EXISTS pms_mews_rates_get_pricing_diff_daily (
    "snapshot_date" DATE NOT NULL,
    "enterprise_id" VARCHAR(64) NOT NULL,
    "entity_id" VARCHAR(256) NOT NULL,
    "changed_metric_name" VARCHAR(256) NOT NULL,
    "old_value" VARCHAR(65535),
    "new_value" VARCHAR(65535),
    "created_at" TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY ("snapshot_date", "enterprise_id", "entity_id", "changed_metric_name")
);
